# base configuration
train_path: 'Preprocessed_Data/train'
eval_path: 'Preprocessed_Data/val'
train_bc: 1
eval_bc: 1
img_sz: [160, 160, 96]
num_epochs: 200

# 新增参数
in_channels: 1
out_channels: 1
feature_dim: 256
num_timesteps: 1000
beta_schedule: linear
learning_rate: 2e-4
weight_decay: 1e-4
use_ema: true

# train process configuration
val_inter: 10
save_inter: 1

# accelerate config
split_batches: False
mixed_precision: 'fp16'
log_with: 'tensorboard'
project_dir: 'weights'
gradient_accumulation_steps: 1
is_debug: True
